### ISSUE TITLE
Return type "json" doesn't seem to work

### ISSUE THREAD

**Issue by davevanhoorn** [BoolCode/appwrite-funcover#8]
Hi BoolCode,

First of all, thanks for creating this. I'm playing around with it and so far it's great. I'm running into a small issue where I'd just like to receive whatever is in the `response` part of the function as parsed JSON, but I always get back the full return.

Is there any way to check if the return type is actually set to `json` in Docker? I did update Appwrite and it created some `.env` and `docker-compose.yml` backups, so I'm not sure if I'm using the right configuration.

**What the response looks like now:**
```
{
  "$id": "64d4dd97df96c8a23858",
  "$createdAt": "2023-08-10T12:52:39.916+00:00",
  "$updatedAt": "2023-08-10T12:52:40.972+00:00",
  "$permissions": [
    "read(\"user:64d23619eba0afd7ea5c\")"
  ],
  "functionId": "stripe-accounts",
  "trigger": "http",
  "status": "completed",
  "statusCode": 200,
  "response": "{\"status\":\"success\",\"title\":\"Stripe notification\",\"message\":\"Stripe account link created.\",\"data\":{\"accountLink\":{\"url\":\"https:\\/\\/connect.stripe.com\\/setup\\/s\\/acct_1NdWHM4JYZLbBFYl\\/4HQfraMpVLXq\"}}}",
  "stdout": "",
  "stderr": "",
  "duration": 1.0414199829101562
}
```

**What I'd like the response to look like (it's the value from `response` above):**
```
"status":"success",
"title":"Stripe notification",
"message":"Stripe account link created.",
"data":{
   "accountLink":{
      "url":"https:\/\/connect.stripe.com\/setup\/s\/acct_1NdWHM4JYZLbBFYl\/4HQfraMpVLXq"
    }
}
```

**My `docker-compose.yml` file looks like this:**
```
funcover:
    image: boolcode/appwrite-funcover:0.0.8
    container_name: funcover
    restart: unless-stopped
    environment:
      - FLATTEN_HEADERS=true
      - PATH_INSTEAD_OF_DOMAIN=true
      - ALLOW_GLOBAL=true
      - PATH_PREFIX=webhooks
      - ENDPOINT=https://appwrite.**********.com/v1
      - RETURN_TYPE=JSON
      # - VERBOSE=true
      # - PATH_AS_DATA=true
      # - DEFAULT_PROJECT=64ce2457de26574cc401
      # - DEFAULT_FUNCTION=64cf5b202afefe32c950
```

**What I tried:**
- change `RETURN_TYPE` to `json` (lowercase)
- change `RETURN_TYPE` to `JSON` (uppercase)
- re-run `docker compose up -d` after every change
- re-deploy the function that gives me the response
- re-run the function from the front-end

Thanks!

**Comment by byawitz** [comment]
Hey @davevanhoorn, thanks for opening this issue, I'll look into it.

To get the current environment variable of any docker container you can run
```shell
docker exec funcover env
```

**Comment by byawitz** [comment]
Just checked it with the following configurations 
```yaml
funcover:
    image: boolcode/appwrite-funcover:0.0.8
    container_name: funcover
    restart: unless-stopped
    environment:
      - ENDPOINT=https://appwrite.**********.com/v1
      - PATH_INSTEAD_OF_DOMAIN=true
      - PATH_PREFIX=v1/webhook
      - PATH_AS_DATA=true
      - ALLOW_GLOBAL=true
      - DEFAULT_PROJECT=test
      - DEFAULT_FUNCTION=test
      - RETURN_TYPE=json
```

Can you try 
1. Change `json` to lowercase and verify there's no space after the value.
2. Run `docker compose down && docker compose up -d` 

To see if returns only the response JSON?

And can you verify the `RETURN_TYPE` env by running the previous comment command?

**Comment by davevanhoorn** [comment]
Thanks @byawitz for the quick reply. I've followed your commands, but still get the full response.

Here's what I did:
 1. Run `docker exec funcover env` - see results below
 2. Checked for a hidden space value after `json`, re-uploaded my `.env` file
 3. Run `docker compose down && docker compose up -d`
 4. Re-run the Appwrite Function from the front-end of my localhost
 
Results of `docker exec funcover env`:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=46662cd838c9
PATH_PREFIX=webhooks
ENDPOINT=https://appwrite.*******.com/v1
RETURN_TYPE=json
FLATTEN_HEADERS=true
PATH_INSTEAD_OF_DOMAIN=true
ALLOW_GLOBAL=true
HOME=/root
```

This is what I use to send the response from the Appwrite Function

```
res.json({
   title: "Appwrite error",
   message: `Stripe Account ID could not be updated.`,
}, 500);
```
 
Might be unrelated, but in the request headers I see `x-appwrite-response-format: 1.0.0`.

**Comment by byawitz** [comment]
Can you share the `traefik` part in your `funcover` declaration?

**Comment by davevanhoorn** [comment]
Sure, here's the full part:

```
funcover:
  image: boolcode/appwrite-funcover:0.0.8
  container_name: funcover
  restart: unless-stopped
  environment:
    - FLATTEN_HEADERS=true
    - PATH_INSTEAD_OF_DOMAIN=true
    - ALLOW_GLOBAL=true
    - PATH_PREFIX=webhooks
    - ENDPOINT=https://appwrite.**********.com/v1
    - RETURN_TYPE=json
    # - VERBOSE=true
    # - PATH_AS_DATA=true
    # - DEFAULT_PROJECT=64ce2457de26574cc401
    # - DEFAULT_FUNCTION=64cf5b202afefe32c950
  networks:
    - appwrite
    - gateway
  labels:
    - traefik.enable=true
    - traefik.constraint-label-stack=appwrite
    - traefik.docker.network=appwrite
    - traefik.http.services.funcover.loadbalancer.server.port=3000
    - traefik.http.routers.funcover-http.entrypoints=appwrite_web
    - traefik.http.routers.funcover-http.rule=PathPrefix(`/webhooks`)
    - traefik.http.routers.funcover-http.service=funcover-third
    - traefik.http.routers.funcover-https.entrypoints=appwrite_websecure
    - traefik.http.routers.funcover-https.rule=PathPrefix(`/webhooks`)
    - traefik.http.routers.funcover-https.service=funcover
    - traefik.http.routers.funcover-https.tls=true
```

Should I remove the comments?
